fix tmp
    [root@110ek fabric-sdk-node]# node test/integration/couchdb-fabricca-tests.js
    info: Successfully constructed a winston logger with configurations debug=console
    module.js:471
        throw err;
        ^

    Error: Cannot find module './api.js'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/root/go/src/github.com/hyperledger/fabric-sdk-node/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:19:11)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)

Signed-off-by: Naoya Horiguchi <n-horiguchi@ah.jp.nec.com>